---
# tasks file for sudo (CentOS specific)

- name: Install sudo packages
  yum: name={{ item }} state=present
  with_items: sudo_packages
  tags: sudo

- name: Create sudoers files
  template: >
    src=sudoers_centos.j2
    dest=/etc/sudoers
    owner=root
    group=root
    mode=0440
    validate='visudo -cf %s'
  tags: sudo
