---
# tasks file for sudo (Ubuntu specific)

- name: Install sudo packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: sudo_packages
  tags: sudo

- name: Create sudoers files
  template: >
    src=sudoers_ubuntu.j2
    dest=/etc/sudoers
    owner=root
    group=root
    mode=0440
    validate='visudo -cf %s'
  tags: sudo
